# Generated by Django 6.0 on 2025-12-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Travel", "Travel"),
                    ("Food", "Food"),
                    ("Accommodation", "Accommodation"),
                    ("Office Supplies", "Office Supplies"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="receipt_details",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
