# Generated by Django 6.0 on 2025-12-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("EMPLOYEE", "Employee"), ("MANAGER", "Manager")],
                default="EMPLOYEE",
                max_length=20,
            ),
        ),
    ]
